name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - edited



jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
        release_files_changed: ${{ steps.filter.outputs.release_files_changed }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            release_files_changed:
              - 'lib/*/version.rb'

  lint:
    needs: check-changes
    if: needs.check-changes.outputs.release_files_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        id: lint_pr_title
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            This repository uses [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for pull request titles to create automated releases.

            If you intend to create a release, please update the pull request title to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

            If you intend to manually manage the release version, please ensure `lib/pore/version.rb` and CHANGELOG is updated.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
          # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
