name: automated-release-pr

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'lib/*/version.rb'
      - 'CHANGELOG.md'
      - '.release-please-manifest.json'

jobs:
  release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release-please
        with:
          skip-github-release: true

      - name: Debug
        if: ${{ steps.release-please.outputs.prs_created == 'true' && steps.release-please.outputs.pr != '' }}
        run: |
          echo "Release PR: ${{ fromJSON(steps.release-please.outputs.pr) }}"
