name: tag-and-release

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby 3.0.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6

    - uses: googleapis/release-please-action@v4
      id: release-please
      with:
        release-type: ruby
